---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: eventstreams
  name: demo-flight-landings
spec:
  config:
    min.insync.replicas: "1"
    retention.ms: "86400000"
  partitions: 1
  replicas: 3
  topicName: FLIGHT.LANDINGS
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: eventstreams
  name: demo-flight-takeoffs
spec:
  config:
    min.insync.replicas: "1"
    retention.ms: "86400000"
  partitions: 1
  replicas: 3
  topicName: FLIGHT.TAKEOFFS
---
